### ISSUE TITLE
InvalidJSONFormatException

### ISSUE THREAD

**Issue by dm-coding** [EstebanMonge/kanboard_imap_tasks#1]
Hi there,

We are getting an invalid JSON format exception when we run the cron task.

>`[07-Dec-2016 14:49:40 UTC] PHP Fatal error:  Uncaught JsonRPC\Exception\InvalidJsonFormatException: Malformed payload in /var/www/app/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Validator/JsonFormatValidator.php:26
Stack trace:
#0 /var/www/app/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Response/ResponseParser.php(86): JsonRPC\Validator\JsonFormatValidator::validate(NULL)
#1 /var/www/app/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(192): JsonRPC\Response\ResponseParser->parse()
#2 /var/www/app/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(176): JsonRPC\Client->sendPayload('{"jsonrpc":"2.0...')
#3 /var/www/app/plugins/Imap/cron.php(49): JsonRPC\Client->execute('getAllProjects')
#4 {main}
  thrown in /var/www/app/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Validator/JsonFormatValidator.php on line 26`

![tasks](https://cloud.githubusercontent.com/assets/1577064/20972374/8e989e68-bc8c-11e6-8c8a-3a198f889bcd.png)

**Comment by EstebanMonge** [comment]
I know about this error is related with characters in mail body or subject. I need work in correct it.\

Can you try fetch email without special characters? Are you sending from with some email client?

**Comment by EstebanMonge** [comment]
I resolved this issue with a complete rewrite and utilization of this library https://github.com/tedious/Fetch
