### ISSUE TITLE
"Finally add a crontab with this line"

### ISSUE THREAD

**Issue by deecey** [EstebanMonge/kanboard_imap_tasks#6]
Hi, sry, I'm a greenhorn with this stuff - where / how can I add a crontab?
Thanx,
Chris

**Comment by EstebanMonge** [comment]
If you have a VPS, with SSH access and GNU/Linux, you can do it with:
crontab -u $USER -e
Where $USER can be root or the web server user, in Debian/Ubuntu based usually is www-data, in RHEL/CentOS based usually is apache.

If you have a shared hosting, you need contact your hosting provider

**Comment by EstebanMonge** [comment]
Sorry about documentation, I have several projects in my work, I put everything in Github to get tracking of changes, the documentation is write in my spare time.

**Comment by EstebanMonge** [comment]
No response, closed

**Comment by deecey** [comment]
Hi EstabanMonge, thanks for your reply, I will contact my provider!
Best Regards
deecey
