### ISSUE TITLE
error creating task

### ISSUE THREAD

**Issue by becto** [EstebanMonge/kanboard_imap_tasks#7]
Hi,

i installed the plugin, but there is something wrong with the cron parser -> i actually don't know, how to fix it -> running debian stretch / php7

``
PHP Notice:  Undefined offset: 1 in /mnt/kanboard/plugins/Imap/cron.php on line 78
PHP Warning:  Invalid argument supplied for foreach() in /mnt/kanboard/plugins/Imap/cron.php on line 83
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid arguments: Invalid params in /mnt/kanboard/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Response/ResponseParser.php:133
Stack trace:
#0 /mnt/kanboard/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Response/ResponseParser.php(103): JsonRPC\Response\ResponseParser->handleExceptions()
#1 /mnt/kanboard/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(194): JsonRPC\Response\ResponseParser->parse()
#2 /mnt/kanboard/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(178): JsonRPC\Client->sendPayload('{"jsonrpc":"2.0...')
#3 /mnt/kanboard/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(126): JsonRPC\Client->execute('createTask', Array)
#4 /mnt/kanboard/plugins/Imap/cron.php(132): JsonRPC\Client->__call('createTask', Array)
#5 {main}
  thrown in /mnt/kanboard/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Response/ResponseParser.php on line 133
``

Can you give a hint, whats wrong with the array?
Greetings Tobias

**Comment by EstebanMonge** [comment]
Hello, have you configured the parameters on Kanboard web GUI?

**Comment by becto** [comment]
Hi,
thanks for supporting me ! -> yes i configured the parameters (except Mail body message, Task description message) -> i left them blank, because i don't know, what to configure.

i exeriment a little bit with the script and might found a problem here:

``
preg_match('~TaskID#\[(.*?)\]~', $message->getSubject(), $output);
$task_id = $output[1];

``

line 77,78 -> if i comment those lines , the script is not functional, but there a no error messages concerning the array $output[1]

regards tobias

**Comment by EstebanMonge** [comment]
I can't reproduce the error, it can be a bug, please give me time to check the script.
